name: CF Scrapper

on:
  schedule:
    - cron: "14 * * * *"  # Runs once every hour at 14 minutes past
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set Locale
        run: |
          sudo apt-get install tzdata locales -y && sudo locale-gen en_US.UTF-8
          sudo localectl set-locale LANG="en_US.UTF-8"
          export LANG="en_US.UTF-8"
          sudo update-locale
          locale -a
          locale
          locale -c -k LC_NUMERIC
          localectl status

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pip
          pip install --upgrade wheel
          pip install -r requirements.txt
          pip install --upgrade pyautogui
          pip install --upgrade python-xlib

      - name: Lint with flake8
        run: |
          pip install flake8
          # Stop the build if there are flake8 issues
          flake8 . --count --show-source --statistics --exclude=temp

      - name: Install Chrome
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt install google-chrome-stable

      - name: Check the console scripts interface
        run: |
          seleniumbase
          sbase

      - name: Install chromedriver
        run: |
          seleniumbase install chromedriver

      - name: Make sure pytest is working
        run: |
          echo "def test_1(): pass" > nothing.py
          pytest nothing.py --uc

      - name: Check which Chrome binaries exist
        run: |
          python -c "import os; print(os.path.exists('/usr/bin/google-chrome'))"
          python -c "import os; print(os.path.exists('/bin/google-chrome-stable'))"
          python -c "import os; print(os.path.exists('/bin/chromium-browser'))"
          python -c "import os; print(os.path.exists('/bin/chromium'))"

      - name: Display Chrome binary that's used
        run: |
          python -c "from seleniumbase.core import detect_b_ver; print(detect_b_ver.get_binary_location('google-chrome'))"
          python -c "from seleniumbase import undetected; print(undetected.find_chrome_executable())"

      - name: Run scraper
        run: python my_first_test.py

      - name: Commit and push data.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data.json || echo "No changes to commit"
          git diff --cached --quiet || git commit -m "Update scraped data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
